# Generated by Django 5.2.4 on 2025-07-31 23:25

from django.db import migrations
from users.models import SGADepartaments

def create_default_departament(apps, schema_editor):
    SGADepartaments.objects.create(departament_name="TESTES")

def delete_default_departament(apps, schema_editor):
    SGADepartaments.objects.all().delete()

class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [(migrations.RunPython(create_default_departament, delete_default_departament))]
