# Generated by Django 5.2.4 on 2025-07-31 14:15

from django.db import migrations
from django.contrib.auth import models


def create_admin_group(apps, schema_editor):
    # FIRST I CREATE THE GROUP
    Groups = models.Group
    created_group = Groups.objects.create(
        name="ADMIN"
    )
    # THEN I ASSIGN EVERY PERMISSION IN OUR DB TO THE ADMIN GROUP
    Permissions = models.Permission
    existing_permissions = Permissions.objects.all()
    created_group.permissions.set(
        existing_permissions
    )
    created_group.save()


def delete_admin_group(apps, schema_editor):
    Groups = models.Group
    created_group = Groups.objects.filter(
        name="ADMIN"
    ).first()
    created_group.permissions.clear()
    created_group.save()
    Groups.objects.filter(
        name="ADMIN"
    ).first().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_create_default_users"),
    ]

    operations = [(migrations.RunPython(create_admin_group, delete_admin_group))]
