# Generated by Django 5.2.4 on 2025-07-24 17:37

from users import models
from django.db import migrations
from datetime import datetime
from django.contrib.auth import get_user_model


def create_default_users(apps, schema_editor):
    # users for devs to play around in development environ
    deparament = models.SGADepartaments.objects.first()
    UserModel = get_user_model()
    UserModel.objects.create_user(
        first_name="Carlos",
        last_name="Ambrósio",
        username="test_user1",
        password="91200399",
        birth_date=datetime.now(),
        departament_id=deparament,
        position="PROGRANADOR SENIOR"
    )
    UserModel.objects.create_user(
        first_name="Aleandro",
        last_name="Matteoni",
        username="test_user2",
        password="91200399",
        birth_date=datetime.now(),
        departament_id=deparament,
        position="PROGRANADOR SENIOR"
    )

def delete_default_users(apps, schema_editor):
    # users for devs to play around in development environ
    UserModel = models.SGAUserModel
    UserModel.objects.all().delete()

class Migration(migrations.Migration):
    dependencies = [("users", "0002_create_default_departament"),]
    operations = [migrations.RunPython(create_default_users, delete_default_users)]
