# Generated by Django 5.2.4 on 2025-07-31 14:24

from django.db import migrations
# Generated by Django 5.2.4 on 2025-07-24 17:37

from django.contrib.auth import models
from django.contrib.auth import get_user_model


def add_test_user_to_admin_group(apps, schema_editor):
    # users for devs to play around in development environ
    UserModel = get_user_model()
    user = UserModel.objects.filter(
        username="test_user1"
    ).first()
    Groups = models.Group
    created_group = Groups.objects.filter(
        name="ADMIN"
    ).first()
    user.groups.set([created_group])
    user.save()

def remove_test_user_from_admin_group(apps, schema_editor):
    UserModel = models.User
    user = UserModel.objects.filter(
        username="test_user1"
    ).first()
    user.groups.clear()
    user.save()
class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_create_default_groups"),
    ]

    operations = [migrations.RunPython(add_test_user_to_admin_group, remove_test_user_from_admin_group)]
