# Generated by Django 5.2.4 on 2025-08-14 00:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="asset_image",
            field=models.ImageField(null=True, upload_to="assets/images/"),
        ),
    ]
