# Generated by Django 5.2.4 on 2025-08-15 23:11

import assets.models.asset_model
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0002_asset_asset_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="asset_lat",
            field=models.CharField(
                max_length=9, validators=[assets.models.asset_model.validate_lat_long]
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="asset_long",
            field=models.CharField(
                max_length=9, validators=[assets.models.asset_model.validate_lat_long]
            ),
        ),
    ]
