# Generated by Django 5.2.4 on 2025-07-24 17:27

from django.db import migrations
from discipline.constants.discipline_constants import DEFAULT_DISCIPLINES

def create_base_disciplines(apps, schema_editor):
    DisciplineModel = apps.get_model("discipline", "DisciplineModel")
    for item in DEFAULT_DISCIPLINES:
        DisciplineModel.objects.create(name=item)

def uncreate_base_disciplines(apps, schema_editor):
    DisciplineModel = apps.get_model("discipline", "DisciplineModel")
    DisciplineModel.objects.all().delete()

class Migration(migrations.Migration):
    dependencies = [
        ("discipline", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_base_disciplines, uncreate_base_disciplines)]
