# Generated by Django 5.2.4 on 2025-08-16 19:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inspections", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InspectionData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("inspection_field", models.CharField(max_length=500)),
                ("inspection_field_data", models.CharField(max_length=500, null=True)),
                ("inspection_field_data_is_file", models.BooleanField(default=False)),
                (
                    "inspection_field_file",
                    models.FileField(null=True, upload_to="assets/inspections/images"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="inspections.inspectionmodel",
                    ),
                ),
            ],
        ),
    ]
